import {getDashboardSummary,getClients,getLoans,getPayments,getInstallments} from '@/lib/data';
import {money} from '@/lib/finance';
import {ExportButtons} from '@/components/reports/export-buttons';

export default async function ReportsPage(){
  const[summary,clients,loans,payments,installments]=await Promise.all([getDashboardSummary(),getClients(),getLoans(),getPayments(),getInstallments()]);
  const ranking=clients.map(x=>({n:x.name,p:payments.filter(y=>y.client_id===x.id).reduce((a,b)=>a+Number(b.amount),0)})).sort((a,b)=>b.p-a.p);
  const loanMap=new Map(loans.map(l=>[l.id,l]));
  const realizedProfit=payments.reduce((sum,p)=>{const loan=loanMap.get(p.loan_id);if(!loan||Number(loan.total_receivable)<=0)return sum;return sum+Number(p.amount)*(Number(loan.expected_profit)/Number(loan.total_receivable));},0);
  const totalPrincipal=loans.reduce((a,b)=>a+Number(b.principal_amount),0);
  return <><div className="page-head"><div><div className="eyebrow">Inteligência</div><h1>Relatórios e backup</h1><div className="muted">Visão consolidada, exportação para Excel, PDF e backup dos dados.</div></div><ExportButtons clients={clients} loans={loans} installments={installments} payments={payments}/></div><div className="stats"><div className="card"><div className="muted">Total emprestado</div><div className="stat-value">{money(totalPrincipal)}</div></div><div className="card"><div className="muted">Total recebido</div><div className="stat-value">{money(summary.totalReceived)}</div></div><div className="card"><div className="muted">Lucro contratado ativo</div><div className="stat-value">{money(summary.expectedProfit)}</div></div><div className="card"><div className="muted">Lucro realizado estimado</div><div className="stat-value">{money(realizedProfit)}</div></div><div className="card"><div className="muted">A receber no mês</div><div className="stat-value">{money(summary.monthExpected)}</div></div><div className="card"><div className="muted">Valor atrasado</div><div className="stat-value">{money(summary.overdue)}</div></div></div><div className="grid-equal" style={{marginTop:16}}><div className="card"><h2>Ranking de clientes por valor recebido</h2><div className="list">{ranking.map((x,k)=><div className="list-row" key={x.n}><div><strong>#{k+1} {x.n}</strong><div className="person-meta">Baseado no histórico de pagamentos ativos</div></div><strong>{money(x.p)}</strong></div>)}</div></div><div className="card"><h2>Indicadores da carteira</h2><div className="list"><div className="list-row"><span>Clientes cadastrados</span><strong>{clients.length}</strong></div><div className="list-row"><span>Empréstimos cadastrados</span><strong>{loans.length}</strong></div><div className="list-row"><span>Parcelas cadastradas</span><strong>{installments.length}</strong></div><div className="list-row"><span>Pagamentos registrados</span><strong>{payments.length}</strong></div></div><div className="alert" style={{marginTop:14}}>“Lucro realizado estimado” distribui proporcionalmente o lucro contratado sobre cada pagamento recebido; não é uma apuração contábil/fiscal.</div></div></div></>
}
